// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQifXWVN61Rj3Ul2N4l7TRL22UR-nXy8',
    appId: '1:3759162813:web:3a281cad2585bedfc4fed4',
    messagingSenderId: '3759162813',
    projectId: 'mobile-assistant-94649',
    authDomain: 'mobile-assistant-94649.firebaseapp.com',
    storageBucket: 'mobile-assistant-94649.firebasestorage.app',
    measurementId: 'G-08PVQF6GD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsC6othPnqXhLdTWHsn3RoI9K7uu2q80',
    appId: '1:3759162813:android:8ed070d607113148c4fed4',
    messagingSenderId: '3759162813',
    projectId: 'mobile-assistant-94649',
    storageBucket: 'mobile-assistant-94649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWVbi2Q92W6tmbDPcuNMM-aHPsSIXpUU',
    appId: '1:3759162813:ios:14c9a1c9eac0cba3c4fed4',
    messagingSenderId: '3759162813',
    projectId: 'mobile-assistant-94649',
    storageBucket: 'mobile-assistant-94649.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgWVbi2Q92W6tmbDPcuNMM-aHPsSIXpUU',
    appId: '1:3759162813:ios:14c9a1c9eac0cba3c4fed4',
    messagingSenderId: '3759162813',
    projectId: 'mobile-assistant-94649',
    storageBucket: 'mobile-assistant-94649.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQifXWVN61Rj3Ul2N4l7TRL22UR-nXy8',
    appId: '1:3759162813:web:30f986577934676dc4fed4',
    messagingSenderId: '3759162813',
    projectId: 'mobile-assistant-94649',
    authDomain: 'mobile-assistant-94649.firebaseapp.com',
    storageBucket: 'mobile-assistant-94649.firebasestorage.app',
    measurementId: 'G-R7C0J21YLC',
  );
}
